--- # My first playbook file
- hosts: apacheweb
  user: user
  sudo: yes
  connection: ssh
  gather_facts: no
  vars:
    playbook_version: 0.1b
  vars_files:
    - conf/copyright.yml
    - conf/webdefaults.yml
  vars_prompt:
    - name: web_womain
      prompt: Web Domain
  tasks: 
   - name: Install web server
     action: yum name=httpd state=installed
     notify: Restart HTTPD
  handlers:
    - name: Restart HTTPD
      action: service name=httpd state=restrted