--- # Deployment example from outline
- hosts: webservers
  user: test
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
  - name: playbook time start
    raw: /usr/bin/date > /home/user/playbookstart.log
  - name: install APACHE
    yum: pkg=httpd state=latest
  - name: start APACHE
    service: name=httpd state=restarted
  - name: verify running APACHE
    command: systemctl status httpd
    register: result
  - debug: var=result
  - name: install client software - telnet
    yum: pkg=telnet state=latest
  - name: install client software - lynx
    yum: pkg=lynx state=latest 
  - name: log all packages
    raw: yum list installed > /home/user/a;;packages.txt
  - name: playbook time end
    raw: /usr/bin/date > /home/user/playbookend.log
    