--- # Deployment example from outline
- hosts: webservers
  user: test
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
  - name: playbook time start
    command: /usr/bin/date
    register: timestamp_start
  - debug: var=timestamp_start
  - name: install APACHE
    yum: pkg=httpd state=latest
    notify: httpd start
  - name: verify running APACHE
    command: systemctl status httpd
    register: result
  - debug: var=result
  - name: install client software - telnet
    yum: pkg=telnet state=latest
  - name: install client software - lynx
    yum: pkg=lynx state=latest 
  - name: log all packages
    commend: yum list installes
    register: list_installed
  - debug: var=list_installed  
  - name: playbook time end
    command: /usr/bin/date
    register: timestamp_stop
  - debug: var=timestamp_stop  
  handlers:
  - name: httpd start
    service: name=httpd state=restarted  